
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingres
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-webapp-svc
            port:
              name: app-svc-port



